[project]
name = "tool-calling-with-react"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "langchain>=1.2.4",
    "langchain-core>=1.2.7",
    "langchain-openai>=1.1.7",
    "typing>=3.10.0.0",
]
